from main import ChatBot
import streamlit as st #Streamlit is a framework for building web applications in Python.

bot = ChatBot() #Instantiate the ChatBot class

st.set_page_config(page_title="Catholic Counterrevolution Bot") #Set the page title
# Sidebar contents (This sidebar is in the left side of the screen)
with st.sidebar:
    st.title("Catholic Counterrevolution Bot")

#Function for generating LLM response
def generate_response(input):
    result = bot.rag_chain.invoke(input) #Invoke the RAG chain with the input to generate a response
    return result

# Store LLM generate response
# When the user enters the chatbot, they see an initial message.
if "messages" not in st.session_state.keys():
    st.session_state.messages = [{
        "role": "assistant", 
        "content": "How can I help you?"
    }]

# Display chat messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# User-provided prompt
# input is a variable that is assigned the value of the input field if it is not None.
if input := st.chat_input():
    st.session_state.messages.append({"role": "user", "content": input})
    with st.chat_message("user"):
        st.write(input)

# Generate a new response if last message is not from assistant
#The messages generated by both the user and the assistant are stored, updating the status of the section.
if st.session_state.messages[-1]["role"] != "assistant":
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            response = generate_response(input)
            st.write(response)
    message = {"role": "assistant", "content": response}
    st.session_state.messages.append(message)